package com.issieboardng.shared

/**
 * KeyboardNeighbors - Keyboard neighbor maps for fuzzy search
 * 
 * Port of ios/Shared/KeyboardNeighbors.swift
 * Auto-generated by build_keyboard_neighbors.js
 * 
 * Maps each character to its physical keyboard neighbors
 * Used by TrieEngine for fuzzy search to weight neighbor typos less harshly
 */
object KeyboardNeighbors {
    
    /** Keyboard neighbors for EN layout */
    val en: Map<Char, List<Char>> = mapOf(
        'q' to listOf('w', 'a'),
        'w' to listOf('q', 'e', 'a', 's'),
        'e' to listOf('w', 'r', 's', 'd'),
        'r' to listOf('e', 't', 'd', 'f'),
        't' to listOf('r', 'y', 'f', 'g'),
        'y' to listOf('t', 'u', 'g', 'h'),
        'u' to listOf('y', 'i', 'h', 'j'),
        'i' to listOf('u', 'o', 'j', 'k'),
        'o' to listOf('i', 'p', 'k', 'l'),
        'p' to listOf('o', 'l'),
        'a' to listOf('s', 'q', 'w', 'z'),
        's' to listOf('a', 'd', 'w', 'e', 'z', 'x'),
        'd' to listOf('s', 'f', 'e', 'r', 'z', 'x', 'c'),
        'f' to listOf('d', 'g', 'r', 't', 'x', 'c', 'v'),
        'g' to listOf('f', 'h', 't', 'y', 'c', 'v', 'b'),
        'h' to listOf('g', 'j', 'y', 'u', 'v', 'b', 'n'),
        'j' to listOf('h', 'k', 'u', 'i', 'b', 'n', 'm'),
        'k' to listOf('j', 'l', 'i', 'o', 'n', 'm'),
        'l' to listOf('k', 'o', 'p', 'm'),
        'z' to listOf('x', 'a', 's', 'd'),
        'x' to listOf('z', 'c', 's', 'd', 'f'),
        'c' to listOf('x', 'v', 'd', 'f', 'g'),
        'v' to listOf('c', 'b', 'f', 'g', 'h'),
        'b' to listOf('v', 'n', 'g', 'h', 'j'),
        'n' to listOf('b', 'm', 'h', 'j', 'k'),
        'm' to listOf('n', 'j', 'k', 'l')
    )

    /** Keyboard neighbors for HE layout */
    val he: Map<Char, List<Char>> = mapOf(
        'ק' to listOf('ר', 'ש', 'ד'),
        'ר' to listOf('ק', 'א', 'ד', 'ג'),
        'א' to listOf('ר', 'ט', 'ג', 'כ'),
        'ט' to listOf('א', 'ו', 'כ', 'ע'),
        'ו' to listOf('ט', 'ן', 'ע', 'י'),
        'ן' to listOf('ו', 'ם', 'י', 'ח'),
        'ם' to listOf('ן', 'פ', 'ח', 'ל'),
        'פ' to listOf('ם', 'ל', 'ך'),
        'ש' to listOf('ד', 'ק', 'ז'),
        'ד' to listOf('ש', 'ג', 'ק', 'ר', 'ז', 'ס'),
        'ג' to listOf('ד', 'כ', 'ר', 'א', 'ס', 'ב'),
        'כ' to listOf('ג', 'ע', 'א', 'ט', 'ב', 'ה'),
        'ע' to listOf('כ', 'י', 'ט', 'ו', 'ה', 'נ'),
        'י' to listOf('ע', 'ח', 'ו', 'ן', 'נ', 'מ'),
        'ח' to listOf('י', 'ל', 'ן', 'ם', 'מ', 'צ'),
        'ל' to listOf('ח', 'ך', 'ם', 'פ', 'צ', 'ת'),
        'ך' to listOf('ל', 'ף', 'פ', 'ת', 'ץ'),
        'ף' to listOf('ך', 'ץ'),
        'ז' to listOf('ס', 'ש', 'ד'),
        'ס' to listOf('ז', 'ב', 'ד', 'ג'),
        'ב' to listOf('ס', 'ה', 'ג', 'כ'),
        'ה' to listOf('ב', 'נ', 'כ', 'ע'),
        'נ' to listOf('ה', 'מ', 'ע', 'י'),
        'מ' to listOf('נ', 'צ', 'י', 'ח'),
        'צ' to listOf('מ', 'ת', 'ח', 'ל'),
        'ת' to listOf('צ', 'ץ', 'ל', 'ך'),
        'ץ' to listOf('ת', 'ך', 'ף')
    )

    /** Keyboard neighbors for AR layout */
    val ar: Map<Char, List<Char>> = mapOf(
        'ض' to listOf('ص', 'ش'),
        'ص' to listOf('ض', 'ث', 'ش', 'س'),
        'ث' to listOf('ص', 'ق', 'س', 'ي'),
        'ق' to listOf('ث', 'ف', 'ي', 'ب'),
        'ف' to listOf('ق', 'غ', 'ب', 'ل'),
        'غ' to listOf('ف', 'ع', 'ل', 'ا'),
        'ع' to listOf('غ', 'ه', 'ا', 'ت'),
        'ه' to listOf('ع', 'خ', 'ت', 'ن'),
        'خ' to listOf('ه', 'ح', 'ن', 'م'),
        'ح' to listOf('خ', 'م'),
        'ش' to listOf('س', 'ض', 'ص', 'ء', 'ؤ'),
        'س' to listOf('ش', 'ي', 'ص', 'ث', 'ؤ', 'ر'),
        'ي' to listOf('س', 'ب', 'ث', 'ق', 'ر', 'ى'),
        'ب' to listOf('ي', 'ل', 'ق', 'ف', 'ى', 'ة'),
        'ل' to listOf('ب', 'ا', 'ف', 'غ', 'ة', 'و'),
        'ا' to listOf('ل', 'ت', 'غ', 'ع', 'و', 'ز'),
        'ت' to listOf('ا', 'ن', 'ع', 'ه', 'ز', 'ظ'),
        'ن' to listOf('ت', 'م', 'ه', 'خ', 'ظ'),
        'م' to listOf('ن', 'خ', 'ح'),
        'ء' to listOf('ؤ', 'ش'),
        'ؤ' to listOf('ء', 'ر', 'ش', 'س'),
        'ر' to listOf('ؤ', 'ى', 'س', 'ي'),
        'ى' to listOf('ر', 'ة', 'ي', 'ب'),
        'ة' to listOf('ى', 'و', 'ب', 'ل'),
        'و' to listOf('ة', 'ز', 'ل', 'ا'),
        'ز' to listOf('و', 'ظ', 'ا', 'ت'),
        'ظ' to listOf('ز', 'ت', 'ن')
    )

    /**
     * Get neighbor map for a given language code
     * @param languageCode Language code (e.g., "en", "he", "ar")
     * @return Map of characters to their keyboard neighbors
     */
    fun neighbors(languageCode: String): Map<Char, List<Char>> {
        return when (languageCode) {
            "en" -> en
            "he" -> he
            "ar" -> ar
            else -> emptyMap() // No neighbors for unknown language
        }
    }
}