const fs = require('fs');
const path = require('path');

/**
 * Build Keyboard Neighbors Script
 * 
 * Parses keyboard JSON files and generates a Swift file containing
 * keyboard neighbor maps for fuzzy search functionality.
 * 
 * Usage: node scripts/build_keyboard_neighbors.js
 */

const KEYBOARDS_DIR = path.join(__dirname, '../keyboards');
const OUTPUT_FILE = path.join(__dirname, '../ios/Shared/KeyboardNeighbors.swift');

// Languages to process
const LANGUAGES = ['en', 'he', 'ar'];

/**
 * Extract key positions from keyboard JSON
 * Returns a 2D grid representation of key positions
 */
function extractKeyPositions(keyboardConfig) {
    const keysets = keyboardConfig.keysets || [];
    const abcKeyset = keysets.find(ks => ks.id === 'abc');
    
    if (!abcKeyset) {
        console.warn(`No 'abc' keyset found for ${keyboardConfig.id}`);
        return [];
    }
    
    const grid = [];
    
    for (const row of abcKeyset.rows) {
        if (row.alwaysInclude) continue; // Skip function rows (space, enter, etc.)
        
        const rowKeys = [];
        let position = 0;
        
        for (const key of row.keys) {
            const width = key.width || 1;
            
            // Only include character keys (those with 'value')
            if (key.value && key.value.length === 1 && !key.hidden && !key.type) {
                rowKeys.push({
                    char: key.value,
                    position: position,
                    width: width
                });
            }
            
            position += width;
        }
        
        if (rowKeys.length > 0) {
            grid.push(rowKeys);
        }
    }
    
    return grid;
}

/**
 * Calculate neighbors for each key
 * A neighbor is a key that is adjacent (horizontally or diagonally adjacent row)
 */
function calculateNeighbors(grid) {
    const neighbors = {};
    
    for (let rowIdx = 0; rowIdx < grid.length; rowIdx++) {
        const row = grid[rowIdx];
        
        for (let keyIdx = 0; keyIdx < row.length; keyIdx++) {
            const key = row[keyIdx];
            const char = key.char;
            const keyNeighbors = new Set();
            
            // Get key center position for distance calculation
            const keyCenter = key.position + (key.width / 2);
            
            // Check same row (left and right neighbors)
            if (keyIdx > 0) {
                keyNeighbors.add(row[keyIdx - 1].char);
            }
            if (keyIdx < row.length - 1) {
                keyNeighbors.add(row[keyIdx + 1].char);
            }
            
            // Check adjacent rows (above and below)
            for (const adjacentRowIdx of [rowIdx - 1, rowIdx + 1]) {
                if (adjacentRowIdx >= 0 && adjacentRowIdx < grid.length) {
                    const adjacentRow = grid[adjacentRowIdx];
                    
                    // Find keys in adjacent row that are close enough
                    for (const adjacentKey of adjacentRow) {
                        const adjacentCenter = adjacentKey.position + (adjacentKey.width / 2);
                        const distance = Math.abs(keyCenter - adjacentCenter);
                        
                        // Consider keys within 1.5 positions as neighbors
                        if (distance < 1.5) {
                            keyNeighbors.add(adjacentKey.char);
                        }
                    }
                }
            }
            
            neighbors[char] = Array.from(keyNeighbors);
        }
    }
    
    return neighbors;
}

/**
 * Generate Swift code for neighbor maps
 */
function generateSwiftCode(allNeighbors) {
    let code = `//
// KeyboardNeighbors.swift
// IssieBoardNG
//
// Auto-generated by build_keyboard_neighbors.js
// DO NOT EDIT MANUALLY
//

import Foundation

/// Keyboard neighbor maps for fuzzy search
/// Maps each character to its physical keyboard neighbors
struct KeyboardNeighbors {
    
`;
    
    for (const [lang, neighbors] of Object.entries(allNeighbors)) {
        code += `    /// Keyboard neighbors for ${lang.toUpperCase()} layout\n`;
        code += `    static let ${lang}: [Character: [Character]] = [\n`;
        
        const entries = Object.entries(neighbors);
        for (let i = 0; i < entries.length; i++) {
            const [char, neighborList] = entries[i];
            const escapedChar = escapeSwiftChar(char);
            const escapedNeighbors = neighborList.map(n => `"${escapeSwiftChar(n)}"`).join(', ');
            const comma = i < entries.length - 1 ? ',' : '';
            code += `        "${escapedChar}": [${escapedNeighbors}]${comma}\n`;
        }
        
        code += `    ]\n\n`;
    }
    
    // Add helper method to get neighbors for a language
    code += `    /// Get neighbor map for a given language code
    static func neighbors(for languageCode: String) -> [Character: [Character]] {
        switch languageCode {
`;
    
    for (const lang of Object.keys(allNeighbors)) {
        code += `        case "${lang}": return ${lang}\n`;
    }
    
    code += `        default: return [:] // No neighbors for unknown language
        }
    }
}
`;
    
    return code;
}

/**
 * Escape special characters for Swift string literals
 */
function escapeSwiftChar(char) {
    if (char === '"') return '\\"';
    if (char === '\\') return '\\\\';
    return char;
}

/**
 * Main function
 */
function main() {
    console.log('🔧 Building keyboard neighbor maps...\n');
    
    const allNeighbors = {};
    
    for (const lang of LANGUAGES) {
        const filePath = path.join(KEYBOARDS_DIR, `${lang}.json`);
        
        if (!fs.existsSync(filePath)) {
            console.warn(`⚠️  Keyboard file not found: ${filePath}`);
            continue;
        }
        
        try {
            const content = fs.readFileSync(filePath, 'utf8');
            const config = JSON.parse(content);
            
            const grid = extractKeyPositions(config);
            console.log(`📋 ${lang.toUpperCase()}: Found ${grid.length} rows`);
            
            for (let i = 0; i < grid.length; i++) {
                const chars = grid[i].map(k => k.char).join(' ');
                console.log(`   Row ${i + 1}: ${chars}`);
            }
            
            const neighbors = calculateNeighbors(grid);
            const keyCount = Object.keys(neighbors).length;
            console.log(`   Generated neighbors for ${keyCount} keys\n`);
            
            allNeighbors[lang] = neighbors;
            
        } catch (err) {
            console.error(`❌ Error processing ${lang}.json:`, err.message);
        }
    }
    
    // Generate Swift code
    const swiftCode = generateSwiftCode(allNeighbors);
    
    // Ensure output directory exists
    const outputDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }
    
    // Write output file
    fs.writeFileSync(OUTPUT_FILE, swiftCode);
    console.log(`✅ Generated: ${OUTPUT_FILE}`);
    console.log(`   Total languages: ${Object.keys(allNeighbors).length}`);
}

main();